apitoken: <put your smartthings api token here>
monitor:
  - temperatureMeasurement
  - illuminanceMeasurement
  - relativeHumidityMeasurement
  - ultravioletIndex
period: 120
influxurl: http://influxdb:8086
influxuser: admin
influxpassword: password
influxdatabase: SmartThings
